# Generated by Django 4.2.30 on 2026-09-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Qabul qilingan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20),
        ),
    ]
