# Generated by Django 4.2.30 on 2026-09-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_masterprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprofile',
            name='work_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='work_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
