# Generated by Django 4.2.30 on 2026-09-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_masterprofile_work_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprofile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
