# Generated by Django 4.2.30 on 2026-09-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_masterprofile_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprofile',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='ratings_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
