# Generated by Django 4.2.30 on 2026-09-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notified_messages',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
