# Generated by Django 4.2.30 on 2026-09-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_notified_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hidden_by_client',
            field=models.BooleanField(default=False),
        ),
    ]
