# Generated by Django 4.2.30 on 2026-09-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_hidden_by_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_from',
            field=models.TimeField(blank=True, null=True, verbose_name="Bo'sh vaqt (boshlanish)"),
        ),
        migrations.AddField(
            model_name='order',
            name='time_to',
            field=models.TimeField(blank=True, null=True, verbose_name="Bo'sh vaqt (tugash)"),
        ),
    ]
