# Generated by Django 4.2.30 on 2026-09-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_time_from_order_time_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
